---
title: "correlation between U1 and U2 with microbiome"
output: html_notebook
---

#libraries
```{r}
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("biomformat")

# if (!requireNamespace('BiocManager', quietly = TRUE))
#     install.packages('BiocManager')
# 
#  BiocManager::install('EnhancedVolcano')

# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("a4Base")
  

library(tidyverse)
library(biomformat)
# library(data.table)
library(compositions)
# library(corrplot)
# library(EnhancedVolcano)
library(a4Base)
library(plotly)
library(grid)
library(gridExtra)
library(ggpubr)

```

# Paths
```{r}
wd <- '../../' 

output_dir = paste0(wd,'results/')
diet.protocols = paste0(output_dir,'diet.protocols/')

data_dir = paste0(wd,'data/')
table_dir = paste0(data_dir, 'tables/')
biom_dir = paste0(data_dir,'silva.feces/')
```

## Create Output Dirs
```{r}
dir.create(output_dir)
dir.create(table_dir)
```

# Data Import
```{r}

L6.rel.clr.U1.U2 <- read_tsv(paste0(table_dir, 'L6.normalized.correlation_06.10.tsv'))
# L6.rel.clr.U1.U2 <- column_to_rownames(L6.rel.clr.U1.U2,'sample')

L2.rel.clr.U1.U2 <- read_tsv(paste0(table_dir, 'L2.normalized.correlation_06.10.tsv'))
# L2.rel.clr.U1.U2 <- column_to_rownames(L2.rel.clr.U1.U2,'sample')

nutr.sum <- read_tsv(paste0(table_dir, 'norm.keto.bls.06.10.tsv'))
nutr.sum$file_name <- gsub(nutr.sum$file_name,pattern='u',replacement = 'U') %>% gsub(pattern = '_',replacement = '.')


conv.sum <- read_tsv(paste0(table_dir, 'conv.cluster.correlation_26.10.tsv'))

cl.sum <- read_tsv(paste0(table_dir, 'nutrient.cluster.correlation_22.10.tsv'))
```

correlation of only U1 (non keto regular diet) and U2 (keto diet) and nutrients, conventional clusters, nutrient clusters on L2(phylum) and L6(genus) level, unrarefied

#dividing data into U1 and U2
```{r}
L2.rel.clr.U1.U2$sample <- str_replace(L2.rel.clr.U1.U2$sample,pattern = 'ST.',replacement = '') %>% 
  str_replace(.,pattern = '0U', replacement = 'U')

L6.rel.clr.U1.U2$sample <- str_replace(L6.rel.clr.U1.U2$sample,pattern = 'ST.',replacement = '') %>% 
  str_replace(.,pattern = '0U', replacement = 'U')

#only U1

L2.U1 <- L2.rel.clr.U1.U2[grepl(pattern = 'U1',L2.rel.clr.U1.U2$sample), ]
names(L2.U1)[names(L2.U1) == 'sample'] <- 'file_name'

L6.U1 <- L6.rel.clr.U1.U2[grepl(pattern = 'U1',L6.rel.clr.U1.U2$sample), ]
names(L6.U1)[names(L6.U1) == 'sample'] <- 'file_name'

L6.U1.r <- L6.U1 %>% column_to_rownames(.,'file_name')
fam.U1 <- sapply(split.default(L6.U1.r, sub('.*_(.*ceae).*', '\\1', names(L6.U1))), rowSums) %>% as.data.frame(.)
fam.U1$file_name <- row.names(fam.U1)

nutr.U1 <- nutr.sum[grepl(pattern = 'U1',nutr.sum$file_name), ]

conv.sumU1 <- conv.sum[grepl(pattern = 'U1',conv.sum$file_name), ]
cl.sumU1 <- cl.sum[grepl(pattern = 'U1',cl.sum$file_name), ]

#only U2

L2.U2 <- L2.rel.clr.U1.U2[grepl(pattern = 'U2',L2.rel.clr.U1.U2$sample), ]
names(L2.U2)[names(L2.U2) == 'sample'] <- 'file_name'

L6.U2 <- L6.rel.clr.U1.U2[grepl(pattern = 'U2',L6.rel.clr.U1.U2$sample), ]
names(L6.U2)[names(L6.U2) == 'sample'] <- 'file_name'

L6.U2.r <- L6.U2 %>% column_to_rownames(.,'file_name')
fam.U2 <- sapply(split.default(L6.U2.r, sub('.*_(.*ceae).*', '\\1', names(L6.U2))), rowSums) %>% as.data.frame(.)
fam.U2$file_name <- row.names(fam.U2)

nutr.U2 <- nutr.sum[grepl(pattern = 'U2',nutr.sum$file_name), ]

conv.sumU2 <- conv.sum[grepl(pattern = 'U2',conv.sum$file_name), ]
cl.sumU2 <- cl.sum[grepl(pattern = 'U2',cl.sum$file_name), ]

```

##only U1
#L6
```{r}
##U1

merge.L6.nutr <- L6.U1 %>% merge(.,nutr.U1,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L6.nutr[is.na(merge.L6.nutr)] <- 0
merge.L6.nutr <- dplyr::select(merge.L6.nutr,everything(),-ends_with('rowsum'))

cor.test.U1 <- merge.L6.nutr %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota.D_2__Methanobacteria.D_3__Methanobacteriales.D_4__Methanobacteriaceae.D_5__Methanobrevibacter:D_0__Eukaryota.D_1__SAR.D_2__Stramenopiles.D_3__Incertae.Sedis.D_4__Blastocystis.D_5__unidentified.guinea.pig.faeces.isolate.U26177) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Energie (kcal)`:`Energie, Gesamt (kcal)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)


cor.test.U1 [is.na(cor.test.U1)] <- 0

p.adj.U1 <- subset(cor.test.U1,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.U1 <- subset(cor.test.U1,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.U1 <- log2(r.cor.U1) %>% as.numeric(.)
cor.test.log.U1 [is.nan(cor.test.log.U1)] <- 0
cor.test.log.U1 [is.infinite(cor.test.log.U1)] <- 0
cor.test.log.U1 <- as.data.frame(cor.test.log.U1)

r.cor.U1[is.nan(r.cor.U1)] <- 0
r.cor.U1[is.infinite(r.cor.U1)] <- 0
r.cor.U1 <- as.data.frame(r.cor.U1)

#y axis -log10 p.value

p.adj.log.U1 <- -log10(p.adj.U1)
p.adj.log.U1[is.infinite(p.adj.log.U1)] <- 0
p.adj.log.U1 <- as.data.frame(p.adj.log.U1)

cor.test.adj.U1 <- cbind(cor.test.U1[ ,c(1,2)],p.adj.log.U1) %>% cbind(.,r.cor.U1) %>% as.data.frame(.)
colnames(cor.test.adj.U1) <- c('nutrient','genus','p.adj.log','estimate')

cor.test.adj.U1 <- cor.test.adj.U1[cor.test.adj.U1$p.adj.log != 0 & cor.test.adj.U1$estimate != 0,]

write_tsv(cor.test.adj.U1,paste0(table_dir,'corr.nutr.L6.U1.tsv'))

sig.U1 <- cor.test.adj.U1[cor.test.adj.U1$p.adj.log >= -log10(0.050) & cor.test.adj.U1$p.adj.log > 0.00000,]
top.sig.U1 <- sig.U1[order(-sig.U1$p.adj.log),]

#volcano plot ggplot()

vp.U1 <- ggplot(cor.test.adj.U1,
    aes(x = `estimate`, y = `p.adj.log`)) +
  geom_point() +
  ggtitle("Volcano plot") +
  xlab("correlation") + 
  ylab("-log10 adjusted p-value")

```

#L2
```{r}
##U1

merge.L2.nutr <- L2.U1 %>% merge(.,nutr.U1,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L2.nutr[is.na(merge.L2.nutr)] <- 0
merge.L2.nutr <- dplyr::select(merge.L2.nutr,everything(),-ends_with('rowsum'))

cor.test <- merge.L2.nutr %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota:D_0__Eukaryota.D_1__SAR) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Energie (kcal)`:`Energie, Gesamt (kcal)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test [is.na(cor.test)] <- 0

p.adj <- subset(cor.test,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor <- subset(cor.test,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log <- log2(r.cor) %>% as.numeric(.)
cor.test.log [is.nan(cor.test.log)] <- 0
cor.test.log [is.infinite(cor.test.log)] <- 0
cor.test.log <- as.data.frame(cor.test.log)

r.cor[is.nan(r.cor)] <- 0
r.cor[is.infinite(r.cor)] <- 0
r.cor<- as.data.frame(r.cor)

#y axis -log10 p.value

p.adj.log <- -log10(p.adj)
p.adj.log[is.infinite(p.adj.log)] <- 0
p.adj.log <- as.data.frame(p.adj.log)

cor.test.adj <- cbind(cor.test[ ,c(1,2)],p.adj.log) %>% cbind(.,r.cor) %>% as.data.frame(.)
colnames(cor.test.adj) <- c('nutrient','phylum','p.adj.log','estimate')

cor.test.adj <- cor.test.adj[cor.test.adj$p.adj.log != 0 & cor.test.adj$estimate != 0,]

write_tsv(cor.test.adj,paste0(table_dir,'corr.nutr.L2.U1.tsv'))

sig <- cor.test.adj[cor.test.adj$p.adj.log <= 0.050 & cor.test.adj$p.adj.log > 0.00000,]
top.sig <- sig[order(-sig$p.adj.log ),]

#volcano plot ggplot()

vp <- ggplot(cor.test.adj,
    aes(x = `estimate`, y = `p.adj.log`)) +
  geom_point() +
  ggtitle("Volcano plot") +
  xlab("correlation") + 
  ylab("-log10 adjusted p-value")

```

#family
```{r}
merge.fam.nutr <- fam.U1 %>% merge(.,nutr.U1,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.fam.nutr[is.na(merge.fam.nutr)] <- 0
merge.fam.nutr <- dplyr::select(merge.fam.nutr,everything(),-ends_with('rowsum'))

cor.test.U1.fam <- merge.fam.nutr %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", Acidaminococcaceae:Xanthomonadaceae) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Energie (kcal)`:`Energie, Gesamt (kcal)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.U1.fam[is.na(cor.test.U1.fam)] <- 0

p.adj.U1.fam <- subset(cor.test.U1.fam,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.U1.fam <- subset(cor.test.U1.fam,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.U1.fam <- log2(r.cor.U1.fam) %>% as.numeric(.)
cor.test.log.U1.fam [is.nan(cor.test.log.U1.fam)] <- 0
cor.test.log.U1.fam [is.infinite(cor.test.log.U1.fam)] <- 0
cor.test.log.U1.fam <- as.data.frame(cor.test.log.U1.fam)

r.cor.U1.fam[is.nan(r.cor.U1.fam)] <- 0
r.cor.U1.fam[is.infinite(r.cor.U1.fam)] <- 0
r.cor.U1.fam <- as.data.frame(r.cor.U1.fam)

#y axis -log10 p.value

p.adj.log.U1.fam <- -log10(p.adj.U1.fam)
p.adj.log.U1.fam[is.infinite(p.adj.log.U1.fam)] <- 0
p.adj.log.U1.fam <- as.data.frame(p.adj.log.U1.fam)

cor.test.adj.U1.fam <- cbind(cor.test.U1.fam[ ,c(1,2)],p.adj.log.U1.fam) %>% cbind(.,r.cor.U1.fam) %>% as.data.frame(.)
colnames(cor.test.adj.U1.fam) <- c('nutrient','family U1','p.adj.log','estimate')

cor.test.adj.U1.fam <- cor.test.adj.U1.fam[cor.test.adj.U1.fam$p.adj.log != 0 & cor.test.adj.U1.fam$estimate != 0,]

write_tsv(cor.test.adj.U1.fam,paste0(table_dir,'corr.nutr.fam.U1.tsv'))

sig.U1.fam <- cor.test.adj.U1.fam[cor.test.adj.U1.fam$p.adj.log <= 0.050 & cor.test.adj.U1.fam$p.adj.log > 0.00000,]
top.sig.U1.fam <- sig.U1.fam[order(-sig.U1.fam$p.adj.log),]
```

##only U2
#L6
```{r}
##U1

merge.L6.nutr <- L6.U2 %>% merge(.,nutr.U2,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L6.nutr[is.na(merge.L6.nutr)] <- 0
merge.L6.nutr <- dplyr::select(merge.L6.nutr,everything(),-ends_with('rowsum'))

cor.test.U2 <- merge.L6.nutr %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota.D_2__Methanobacteria.D_3__Methanobacteriales.D_4__Methanobacteriaceae.D_5__Methanobrevibacter:D_0__Eukaryota.D_1__SAR.D_2__Stramenopiles.D_3__Incertae.Sedis.D_4__Blastocystis.D_5__unidentified.guinea.pig.faeces.isolate.U26177) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Energie (kcal)`:`Energie, Gesamt (kcal)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.U2 [is.na(cor.test.U2)] <- 0

p.adj.U2 <- subset(cor.test.U2,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.U2 <- subset(cor.test.U2,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.U2 <- log2(r.cor.U2) %>% as.numeric(.)
cor.test.log.U2 [is.nan(cor.test.log.U2)] <- 0
cor.test.log.U2 [is.infinite(cor.test.log.U2)] <- 0
cor.test.log.U2 <- as.data.frame(cor.test.log.U2)

r.cor.U2[is.nan(r.cor.U2)] <- 0
r.cor.U2[is.infinite(r.cor.U2)] <- 0
r.cor.U2 <- as.data.frame(r.cor.U2)

#y axis -log10 p.value

p.adj.log.U2 <- -log10(p.adj.U2)
p.adj.log.U2[is.infinite(p.adj.log.U2)] <- 0
p.adj.log.U2 <- as.data.frame(p.adj.log.U2)

cor.test.adj.U2 <- cbind(cor.test.U2[ ,c(1,2)],p.adj.log.U2) %>% cbind(.,r.cor.U2) %>% as.data.frame(.)
colnames(cor.test.adj.U2) <- c('nutrient','genus','p.adj.log','estimate')

cor.test.adj.U2 <- cor.test.adj.U2[cor.test.adj.U2$p.adj.log != 0 & cor.test.adj.U2$estimate != 0,]

write_tsv(cor.test.adj.U2,paste0(table_dir,'corr.nutr.L6.U2.tsv'))

sig.U2 <- cor.test.adj.U2[cor.test.adj.U2$p.adj.log >= -log10(0.050) & cor.test.adj.U2$p.adj.log > 0.00000,]
top.sig.U2 <- sig.U2[order(-sig.U2$p.adj.log),]

#volcano plot ggplot()

vp.U2 <- ggplot(cor.test.adj.U2,
    aes(x = `estimate`, y = `p.adj.log`)) +
  geom_point() +
  ggtitle("Volcano plot") +
  xlab("correlation") + 
  ylab("-log10 adjusted p-value")

```

#L2
```{r}
#only U1

merge.L2.nutr <- L2.U2 %>% merge(.,nutr.U2,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L2.nutr[is.na(merge.L2.nutr)] <- 0
merge.L2.nutr <- dplyr::select(merge.L2.nutr,everything(),-ends_with('rowsum'))

cor.test <- merge.L2.nutr %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota:D_0__Eukaryota.D_1__SAR) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Energie (kcal)`:`Energie, Gesamt (kcal)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test [is.na(cor.test)] <- 0

p.adj <- subset(cor.test,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor <- subset(cor.test,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log <- log2(r.cor) %>% as.numeric(.)
cor.test.log [is.nan(cor.test.log)] <- 0
cor.test.log [is.infinite(cor.test.log)] <- 0
cor.test.log <- as.data.frame(cor.test.log)

r.cor[is.nan(r.cor)] <- 0
r.cor[is.infinite(r.cor)] <- 0
r.cor<- as.data.frame(r.cor)

#y axis -log10 p.value

p.adj.log <- -log10(p.adj)
p.adj.log[is.infinite(p.adj.log)] <- 0
p.adj.log <- as.data.frame(p.adj.log)

cor.test.adj <- cbind(cor.test[ ,c(1,2)],p.adj.log) %>% cbind(.,r.cor) %>% as.data.frame(.)
colnames(cor.test.adj) <- c('nutrient','phylum','p.adj.log','estimate')

cor.test.adj <- cor.test.adj[cor.test.adj$p.adj.log != 0 & cor.test.adj$estimate != 0,]

write_tsv(cor.test.adj,paste0(table_dir,'corr.nutr.L2.U2.tsv'))

sig <- cor.test.adj[cor.test.adj$p.adj.log <= 0.050 & cor.test.adj$p.adj.log > 0.00000,]
top.sig <- sig[order(-sig$p.adj.log ),]

#volcano plot ggplot()

vp <- ggplot(cor.test.adj,
    aes(x = `estimate`, y = `p.adj.log`)) +
  geom_point() +
  ggtitle("Volcano plot") +
  xlab("correlation") + 
  ylab("-log10 adjusted p-value")

```

#family
```{r}
merge.fam.nutr <- fam.U2 %>% merge(.,nutr.U2,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.fam.nutr[is.na(merge.fam.nutr)] <- 0
merge.fam.nutr <- dplyr::select(merge.fam.nutr,everything(),-ends_with('rowsum'))

cor.test.U2.fam <- merge.fam.nutr %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", Acidaminococcaceae:Xanthomonadaceae) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Energie (kcal)`:`Energie, Gesamt (kcal)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.U2.fam[is.na(cor.test.U2.fam)] <- 0

p.adj.U2.fam <- subset(cor.test.U2.fam,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.U2.fam <- subset(cor.test.U2.fam,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.U2.fam <- log2(r.cor.U2.fam) %>% as.numeric(.)
cor.test.log.U2.fam [is.nan(cor.test.log.U2.fam)] <- 0
cor.test.log.U2.fam [is.infinite(cor.test.log.U2.fam)] <- 0
cor.test.log.U2.fam <- as.data.frame(cor.test.log.U2.fam)

r.cor.U2.fam[is.nan(r.cor.U2.fam)] <- 0
r.cor.U2.fam[is.infinite(r.cor.U2.fam)] <- 0
r.cor.U2.fam <- as.data.frame(r.cor.U2.fam)

#y axis -log10 p.value

p.adj.log.U2.fam <- -log10(p.adj.U2.fam)
p.adj.log.U2.fam[is.infinite(p.adj.log.U2.fam)] <- 0
p.adj.log.U2.fam <- as.data.frame(p.adj.log.U2.fam)

cor.test.adj.U2.fam <- cbind(cor.test.U2.fam[ ,c(1,2)],p.adj.log.U2.fam) %>% cbind(.,r.cor.U2.fam) %>% as.data.frame(.)
colnames(cor.test.adj.U2.fam) <- c('nutrient','family U2','p.adj.log','estimate')

cor.test.adj.U2.fam <- cor.test.adj.U2.fam[cor.test.adj.U2.fam$p.adj.log != 0 & cor.test.adj.U2.fam$estimate != 0,]

write_tsv(cor.test.adj.U2.fam,paste0(table_dir,'corr.nutr.fam.U2.tsv'))

sig.U2.fam <- cor.test.adj.U2.fam[cor.test.adj.U2.fam$p.adj.log <= 0.050 & cor.test.adj.U2.fam$p.adj.log > 0.00000,]
top.sig.U2.fam <- sig.U2.fam[order(-sig.U2.fam$p.adj.log),]
```

##only U1
#L6 conv clusters
```{r}
##U1

merge.L6.convU1 <- L6.U1 %>% merge(.,conv.sumU1,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L6.convU1[is.na(merge.L6.convU1)] <- 0
merge.L6.convU1 <- dplyr::select(merge.L6.convU1,everything(),-ends_with('rowsum'))

cor.test.convU1 <- merge.L6.convU1 %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota.D_2__Methanobacteria.D_3__Methanobacteriales.D_4__Methanobacteriaceae.D_5__Methanobrevibacter:D_0__Eukaryota.D_1__SAR.D_2__Stramenopiles.D_3__Incertae.Sedis.D_4__Blastocystis.D_5__unidentified.guinea.pig.faeces.isolate.U26177) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Alkoholfreie Getränke`:`Wurst, Fleischwaren`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.convU1 [is.na(cor.test.convU1)] <- 0

p.adj.convU1 <- subset(cor.test.convU1,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.convU1 <- subset(cor.test.convU1,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.convU1 <- log2(r.cor.convU1) %>% as.numeric(.)
cor.test.log.convU1 [is.nan(cor.test.log.convU1)] <- 0
cor.test.log.convU1 [is.infinite(cor.test.log.convU1)] <- 0
cor.test.log.convU1 <- as.data.frame(cor.test.log.convU1)

r.cor.convU1[is.nan(r.cor.convU1)] <- 0
r.cor.convU1[is.infinite(r.cor.convU1)] <- 0
r.cor.convU1 <- as.data.frame(r.cor.convU1)

#y axis -log10 p.value

p.adj.log.convU1 <- -log10(p.adj.convU1)
p.adj.log.convU1[is.infinite(p.adj.log.convU1)] <- 0
p.adj.log.convU1 <- as.data.frame(p.adj.log.convU1)

cor.test.adj.convU1 <- cbind(cor.test.convU1[ ,c(1,2)],p.adj.log.convU1) %>% cbind(.,r.cor.convU1) %>% as.data.frame(.)
colnames(cor.test.adj.convU1) <- c('conv cluster','genus','p.adj.log','estimate')

cor.test.adj.convU1 <- cor.test.adj.convU1[cor.test.adj.convU1$p.adj.log != 0 & cor.test.adj.convU1$estimate != 0,]

write_tsv(cor.test.adj.convU1,paste0(table_dir,'corr.convclust.L6.U1.tsv'))

sig.convU1 <- cor.test.adj.convU1[cor.test.adj.convU1$p.adj.log >= -log10(0.05) & cor.test.adj.convU1$p.adj.log > 0.00000,]
top.sig.convU1 <- sig.convU1[order(-sig.convU1$p.adj.log),]

```
# L6 nutr cluster
```{r}
##U1

merge.L6.nutrU1 <- L6.U1 %>% merge(.,cl.sumU1,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L6.nutrU1[is.na(merge.L6.nutrU1)] <- 0
merge.L6.nutrU1 <- dplyr::select(merge.L6.nutrU1,everything(),-ends_with('rowsum'))

cor.test.nutrU1 <- merge.L6.nutrU1 %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota.D_2__Methanobacteria.D_3__Methanobacteriales.D_4__Methanobacteriaceae.D_5__Methanobrevibacter:D_0__Eukaryota.D_1__SAR.D_2__Stramenopiles.D_3__Incertae.Sedis.D_4__Blastocystis.D_5__unidentified.guinea.pig.faeces.isolate.U26177) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `menue compounds (1)`:`sweets (15)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.nutrU1 [is.na(cor.test.nutrU1)] <- 0

p.adj.nutrU1 <- subset(cor.test.nutrU1,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.nutrU1 <- subset(cor.test.nutrU1,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.nutrU1 <- log2(r.cor.nutrU1) %>% as.numeric(.)
cor.test.log.nutrU1 [is.nan(cor.test.log.nutrU1)] <- 0
cor.test.log.nutrU1 [is.infinite(cor.test.log.nutrU1)] <- 0
cor.test.log.nutrU1 <- as.data.frame(cor.test.log.nutrU1)

r.cor.nutrU1[is.nan(r.cor.nutrU1)] <- 0
r.cor.nutrU1[is.infinite(r.cor.nutrU1)] <- 0
r.cor.nutrU1 <- as.data.frame(r.cor.nutrU1)

#y axis -log10 p.value

p.adj.log.nutrU1 <- -log10(p.adj.nutrU1)
p.adj.log.nutrU1[is.infinite(p.adj.log.nutrU1)] <- 0
p.adj.log.nutrU1 <- as.data.frame(p.adj.log.nutrU1)

cor.test.adj.nutrU1 <- cbind(cor.test.nutrU1[ ,c(1,2)],p.adj.log.nutrU1) %>% cbind(.,r.cor.nutrU1) %>% as.data.frame(.)
colnames(cor.test.adj.nutrU1) <- c('nutr cluster','genus','p.adj.log','estimate')

cor.test.adj.nutrU1 <- cor.test.adj.nutrU1[cor.test.adj.nutrU1$p.adj.log != 0 & cor.test.adj.nutrU1$estimate != 0,]

write_tsv(cor.test.adj.nutrU1,paste0(table_dir,'corr.nutrclust.L6.U1.tsv'))

sig.nutrU1 <- cor.test.adj.nutrU1[cor.test.adj.nutrU1$p.adj.log >= -log10(0.05) & cor.test.adj.nutrU1$p.adj.log > 0.00000,]
top.sig.nutrU1 <- sig.nutrU1[order(-sig.nutrU1$p.adj.log),]


```

##only U2
#L6 conv clusters
```{r}
##U1

merge.L6.convU2 <- L6.U2 %>% merge(.,conv.sumU2,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L6.convU2[is.na(merge.L6.convU2)] <- 0
merge.L6.convU2 <- dplyr::select(merge.L6.convU2,everything(),-ends_with('rowsum'))

cor.test.convU2 <- merge.L6.convU2 %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota.D_2__Methanobacteria.D_3__Methanobacteriales.D_4__Methanobacteriaceae.D_5__Methanobrevibacter:D_0__Eukaryota.D_1__SAR.D_2__Stramenopiles.D_3__Incertae.Sedis.D_4__Blastocystis.D_5__unidentified.guinea.pig.faeces.isolate.U26177) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `Alkoholfreie Getränke`:`Wurst, Fleischwaren`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.convU2 [is.na(cor.test.convU2)] <- 0

p.adj.convU2 <- subset(cor.test.convU2,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.convU2 <- subset(cor.test.convU2,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.convU2 <- log2(r.cor.convU2) %>% as.numeric(.)
cor.test.log.convU2 [is.nan(cor.test.log.convU2)] <- 0
cor.test.log.convU2 [is.infinite(cor.test.log.convU2)] <- 0
cor.test.log.convU2 <- as.data.frame(cor.test.log.convU2)

r.cor.convU2[is.nan(r.cor.convU2)] <- 0
r.cor.convU2[is.infinite(r.cor.convU2)] <- 0
r.cor.convU2 <- as.data.frame(r.cor.convU2)

#y axis -log10 p.value

p.adj.log.convU2 <- -log10(p.adj.convU2)
p.adj.log.convU2[is.infinite(p.adj.log.convU2)] <- 0
p.adj.log.convU2 <- as.data.frame(p.adj.log.convU2)

cor.test.adj.convU2 <- cbind(cor.test.convU2[ ,c(1,2)],p.adj.log.convU2) %>% cbind(.,r.cor.convU2) %>% as.data.frame(.)
colnames(cor.test.adj.convU2) <- c('nutrient','genus','p.adj.log','estimate')

cor.test.adj.convU2 <- cor.test.adj.convU2[cor.test.adj.convU2$p.adj.log != 0 & cor.test.adj.convU2$estimate != 0,]

write_tsv(cor.test.adj.convU2,paste0(table_dir,'corr.convrclust.L6.U2.tsv'))

sig.convU2 <- cor.test.adj.convU2[cor.test.adj.convU2$p.adj.log >= -log10(0.050) & cor.test.adj.convU2$p.adj.log > 0.00000,]
top.sig.convU2 <- sig.convU2[order(-sig.convU2$p.adj.log),]

```

# L6 nutr cluster
```{r}
##U2

merge.L6.nutrU2 <- L6.U2 %>% merge(.,cl.sumU2,by = 'file_name',all.x=T,all.y = T) %>% column_to_rownames(.,'file_name')

merge.L6.nutrU2[is.na(merge.L6.nutrU2)] <- 0
merge.L6.nutrU2 <- dplyr::select(merge.L6.nutrU2,everything(),-ends_with('rowsum'))

cor.test.nutrU2 <- merge.L6.nutrU2 %>% 
  pivot_longer(names_to = "variable_right", values_to = "value_right", D_0__Archaea.D_1__Euryarchaeota.D_2__Methanobacteria.D_3__Methanobacteriales.D_4__Methanobacteriaceae.D_5__Methanobrevibacter:D_0__Eukaryota.D_1__SAR.D_2__Stramenopiles.D_3__Incertae.Sedis.D_4__Blastocystis.D_5__unidentified.guinea.pig.faeces.isolate.U26177) %>% 
  pivot_longer(names_to = "variable_left", values_to = "value_left", `menue compounds (1)`:`sweets (15)`) %>% 
  group_by(variable_left, variable_right) %>% 
  
  summarize(p.value = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$p.value,
         estimate = broom::tidy(cor.test(value_left, value_right,method = 'spearman'))$estimate)

cor.test.nutrU2 [is.na(cor.test.nutrU2)] <- 0

p.adj.nutrU2 <- subset(cor.test.nutrU2,select = `p.value`) %>% data.matrix(.) %>% p.adjust(.,method = 'fdr')
r.cor.nutrU2 <- subset(cor.test.nutrU2,select = `estimate`) %>% data.matrix(.)

#x axis log2 correlation

cor.test.log.nutrU2 <- log2(r.cor.nutrU2) %>% as.numeric(.)
cor.test.log.nutrU2 [is.nan(cor.test.log.nutrU2)] <- 0
cor.test.log.nutrU2 [is.infinite(cor.test.log.nutrU2)] <- 0
cor.test.log.nutrU2 <- as.data.frame(cor.test.log.nutrU2)

r.cor.nutrU2[is.nan(r.cor.nutrU2)] <- 0
r.cor.nutrU2[is.infinite(r.cor.nutrU2)] <- 0
r.cor.nutrU2 <- as.data.frame(r.cor.nutrU2)

#y axis -log10 p.value

p.adj.log.nutrU2 <- -log10(p.adj.nutrU2)
p.adj.log.nutrU2[is.infinite(p.adj.log.nutrU2)] <- 0
p.adj.log.nutrU2 <- as.data.frame(p.adj.log.nutrU2)

cor.test.adj.nutrU2 <- cbind(cor.test.nutrU2[ ,c(1,2)],p.adj.log.nutrU2) %>% cbind(.,r.cor.nutrU2) %>% as.data.frame(.)
colnames(cor.test.adj.nutrU2) <- c('nutrient','genus','p.adj.log','estimate')

cor.test.adj.nutrU2 <- cor.test.adj.nutrU2[cor.test.adj.nutrU2$p.adj.log != 0 & cor.test.adj.nutrU2$estimate != 0,]

write_tsv(cor.test.adj.nutrU2,paste0(table_dir,'corr.nutrclust.L6.U2.tsv'))

sig.nutrU2 <- cor.test.adj.nutrU2[cor.test.adj.nutrU2$p.adj.log >= -log10(0.050) & cor.test.adj.nutrU2$p.adj.log > 0.00000,]
top.sig.nutrU2 <- sig.nutrU2[order(-sig.nutrU2$p.adj.log),]

```
