---
title: "Bray Curtis"
output: html_notebook
---

#libraries
```{r}
library(tidyverse)
library(ecodist)
library(ggplot2)
library(plotly)
library(vegan)

library(ggpubr)
```

# Paths
```{r}
wd <- '../../' 

output_dir = paste0(wd,'results/')
diet.protocols = paste0(output_dir,'diet.protocols/')

data_dir = paste0(wd,'data/')
table_dir = paste0(data_dir, 'tables/')
biom_dir = paste0(data_dir,'silva.feces/')
```

## Create Output Dirs
```{r}
dir.create(output_dir)
dir.create(table_dir)
```

#Data Import
```{r}
#otu_table per week
otu.week <- read_tsv(paste0(table_dir,'otu.conv.uw.19.08.tsv'))

otu.week <- as.data.frame(otu.week)
row.names(otu.week) <- otu.week$file_name
otu.week <- otu.week[ ,-1]

#otu_table per day
otu.day <- read_tsv(paste0(table_dir,'otu.conv.uw.samp.19.08.tsv'))

otu.day  <- as.data.frame(otu.day )
row.names(otu.day) <- otu.day$sample_day
otu.day  <- otu.day [ ,-1]


k.bls_prodi <- read_tsv(paste0(table_dir,'k.bls_prodi_13_08.tsv'))

k.bls_prodi$file_name <- gsub(k.bls_prodi$file_name,pattern='u',replacement = 'U') %>% gsub(pattern = '_',replacement = '.')

k.bls_prodi$Sex[k.bls_prodi$Sex == FALSE] <- 'female'
k.bls_prodi$Sex[is.na(k.bls_prodi$Sex)] <- 0
k.bls_prodi <-k.bls_prodi[complete.cases(k.bls_prodi), ]
k.bls_prodi$Sex[k.bls_prodi$Sex == 0] <- 'male'

#clusters
conv.clust <- read_tsv(paste0(table_dir,'conv.clust.df.01.10.tsv')) %>% column_to_rownames(.,'file_name')
nutr.clust <- read_tsv(paste0(table_dir,'nutr.clust.df.01.10.tsv')) %>% column_to_rownames(.,'file_name')

```

#foods at similar quantities
How many identical foods were consumed at similar quantities?
```{r}
#foods as specy

bc.week <- vegdist(otu.week, method="bray")
bc.day <- vegdist(otu.day, method="bray")
pcoa_bc.week <- ape::pcoa(bc.week)
pcoa_bc.day <- ape::pcoa(bc.day)


#Phenotype
metadata.pheno <- 
  k.bls_prodi %>% 
  dplyr::select(file_name:Phenotype) %>% 
  distinct() %>%
  dplyr::rename(Name = file_name)
wnw <- pcoa_bc.week$vectors %>%  
  as.data.frame(.) %>% 
  rownames_to_column('Name') %>% 
  dplyr::select(Name, Axis.1:Axis.5) %>%
  separate(Name, remove = F, into = c('Sample','U'), sep = '[.]') %>% 
  left_join(., metadata.pheno, by = 'Name') %>%
  mutate(Pheno = ifelse(Phenotype == 'not classified', NA, Phenotype)) %>% 
  ggplot(aes(Axis.1, Axis.2, label = Name)) + 
  geom_point(aes(fill = U, alpha = Pheno),
    shape = 21, col = 'black', size = 4) + ggtitle('PcoA Bray-Curtis similarity\nsamples per week')


#Sex
metadata.sex <- 
  k.bls_prodi %>% 
  dplyr::select(file_name:Sex) %>% 
  distinct() %>% 
  dplyr::rename(Name = file_name)
k <- pcoa_bc.day$vectors %>%  
  as.data.frame(.) %>% 
  rownames_to_column('Name') %>% 
  dplyr::select(Name, Axis.1:Axis.5) %>%
  separate(Name, remove = F, into = c('Sample','U'), sep = '[.]') %>% 
  left_join(., metadata.sex, by = 'Name') %>%
  mutate(Pheno = ifelse(Sex == 'not classified', NA, Sex)) %>% 
  ggplot(aes(Axis.1, Axis.2)) + 
  geom_point(aes(fill = U, alpha = Sex),
    shape = 21, col = 'black', size = 4) + ggtitle('PcoA Bray-Curtis similarity\nsamples per day')
```

#clusters at similar quantities
How many identical clusters were consumed at similar quantities?
```{r}
#conventional clusters

bc.conv <- vegdist(conv.clust, method="bray")##noNA
pcoa_bc.conv <- ape::pcoa(bc.conv)##noNA

#varinace

get_explained_variance <- function(pcoa) {
  return(paste0(round(pcoa$values$Rel_corr_eig * 100, 2), '%'))
}
get_explained_variance(pcoa_bc.conv)[1:2]

pcoa_bc.conv$vectors <- pcoa_bc.conv$vectors %>% as.data.frame(.)
var.bcAxis.1 <- var(pcoa_bc.conv$vectors$Axis.1)## 0.02269335
var.bcAxis.2 <- var(pcoa_bc.conv$vectors$Axis.2)## 0.0121807

#Phenotype
metadata.pheno <- 
  k.bls_prodi %>% 
  dplyr::select(file_name:Phenotype) %>% 
  distinct() %>%
  dplyr::rename(Name = file_name)
conv.pheno <- pcoa_bc.conv$vectors %>%  
  as.data.frame(.) %>% 
  rownames_to_column('Name') %>% 
  dplyr::select(Name, Axis.1:Axis.5) %>%
  
  separate(Name, remove = F, into = c('Sample','U'), sep = '[.]') %>% 
  left_join(., metadata.pheno, by = 'Name') %>%
  mutate(Pheno = ifelse(Phenotype == 'not classified', NA, Phenotype)) %>% 
  ggplot(aes(Axis.1, Axis.2, label = Name)) + 
  geom_point(aes(fill = U, alpha = Pheno),
    shape = 21, col = 'black', size = 4) + ggtitle('PcoA Bray-Curtis similarity\nconventional clusters')


# ggplotly(wnw,tooltip = c('x','y','text'))

#Sex
metadata.sex <- 
  k.bls_prodi %>% 
  dplyr::select(file_name:Sex) %>% 
  distinct() %>% 
  dplyr::rename(Name = file_name)
conv.sex <- pcoa_bc.conv$vectors %>%  
  as.data.frame(.) %>% 
  rownames_to_column('Name') %>% 
  dplyr::select(Name, Axis.1:Axis.5) %>%
  separate(Name, remove = F, into = c('Sample','U'), sep = '[.]') %>% 
  left_join(., metadata.sex, by = 'Name') %>%
  mutate(Pheno = ifelse(Sex == 'not classified', NA, Sex)) %>% 
  ggplot(aes(Axis.1, Axis.2)) + 
  geom_point(aes(fill = U, alpha = Sex),
    shape = 21, col = 'black', size = 4) + ggtitle('PcoA Bray-Curtis similarity\nconventional clusters')


#nutrient clusters

bc.nutr <- vegdist(nutr.clust, method="bray")##noNA
pcoa_bc.nutr <- ape::pcoa(bc.nutr)##noNA

#varinace

get_explained_variance(pcoa_bc.nutr)[1:2]

pcoa_bc.nutr$vectors <- pcoa_bc.nutr$vectors %>% as.data.frame(.)
var.bcnutAxis.1 <- var(pcoa_bc.nutr$vectors$Axis.1)##0.01496785
var.bcnutAxis.2 <- var(pcoa_bc.nutr$vectors$Axis.2)## 0.01303654

#Phenotype
metadata.pheno <- 
  k.bls_prodi %>% 
  dplyr::select(file_name:Phenotype) %>% 
  distinct() %>%
  dplyr::rename(Name = file_name)
nutr.pheno <- pcoa_bc.nutr$vectors %>%  
  as.data.frame(.) %>% 
  rownames_to_column('Name') %>% 
  dplyr::select(Name, Axis.1:Axis.5) %>%
  separate(Name, remove = F, into = c('Sample','U'), sep = '[.]') %>% 
  left_join(., metadata.pheno, by = 'Name') %>%
  mutate(Pheno = ifelse(Phenotype == 'not classified', NA, Phenotype)) %>% 
  ggplot(aes(Axis.1, Axis.2, label = Name)) + 
  geom_point(aes(fill = U, alpha = Pheno),
    shape = 21, col = 'black', size = 4) + ggtitle('PcoA Bray-Curtis similarity\nnutrient clusters')


# ggplotly(wnw,tooltip = c('x','y','text'))

#Sex
metadata.sex <- 
  k.bls_prodi %>% 
  dplyr::select(file_name:Sex) %>% 
  distinct() %>% 
  dplyr::rename(Name = file_name)
nutr.sex <- pcoa_bc.nutr$vectors %>%  
  as.data.frame(.) %>% 
  rownames_to_column('Name') %>% 
  dplyr::select(Name, Axis.1:Axis.5) %>%
  separate(Name, remove = F, into = c('Sample','U'), sep = '[.]') %>% 
  left_join(., metadata.sex, by = 'Name') %>%
  mutate(Pheno = ifelse(Sex == 'not classified', NA, Sex)) %>% 
  ggplot(aes(Axis.1, Axis.2)) + 
  geom_point(aes(fill = U, alpha = Sex),
    shape = 21, col = 'black', size = 4) + ggtitle('PcoA Bray-Curtis similarity\nnutrient clusters')

```

###export
```{r}
pdf(paste0(output_dir,'bray.curtis.pc.pdf'))

ggarrange(wnw,k , 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

ggarrange(conv.pheno,conv.sex , 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

ggarrange(nutr.pheno,nutr.sex , 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

dev.off()
```

